apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unifiedpush-operator
rules:

# The resources in this group are the CRs that the controllers in this
# operator react to. Nothing in the operator is expected to create or
# delete CRs, so those permissions are not given.
- apiGroups:
  - push.aerogear.org
  resources:
  - pushapplications
  - pushapplications/status
  - pushapplications/finalizers

  - androidvariants
  - androidvariants/status
  - androidvariants/finalizers

  - iosvariants
  - iosvariants/status
  - iosvariants/finalizers

  - webpushvariants
  - webpushvariants/status
  - webpushvariants/finalizers
  verbs:
  - get
  - list
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unifiedpush-operator-ups
rules:

# The resources in this group are the CRs that the controllers in this
# operator react to. Nothing in the operator is expected to create or
# delete CRs, so those permissions are not given.
- apiGroups:
  - push.aerogear.org
  resources:
  - unifiedpushservers
  - unifiedpushservers/status
  - unifiedpushservers/finalizers
  verbs:
  - get
  - list
  - watch
  - update

# For "secondary resources", the operator needs to be able to do
# pretty much everything. The "deletecollection" permission is the
# only one not given here (if it needs to delete more than one
# instance of a kind, it can do them one-by-one.
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Need to be able to check if a namespace is in APP_NAMESPACES
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

# These are needed to be able to run the operator itself
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - unifiedpush-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get

# Needed to be able to create ServiceMonitor for operator & operands
- apiGroups:
  - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
